version: '3.8'

services:
  app1:
    image: app1
    container_name: app1
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url": "jdbc:mysql://mysqldb:3306/app1db?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true",
              "spring.datasource.username": "root",
              "spring.datasource.password": "matias",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'
    networks:
      app_network:
        aliases:
          - mysqldb
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: matias
      MYSQL_DATABASE: app1db
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysqldb", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10
    networks:
      app_network:
        aliases:
          - mysqldb

volumes:
  mysql-data:
networks:
  app_network:
    driver: bridge